
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Josepth', 333, 'CSE');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Kanthi', 5353, 'CSE');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Mathi', 6363, 'CSE');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Rahim', 222, 'CSE');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Ram', 111, 'CSE');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Arunchalam', 2222, 'ECE');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Banu', 55, 'ECE');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Arun', 4333, 'MCA');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Ragu', 4433, 'MCA');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Deva', 5555, 'MEC');
INSERT INTO STUDENTS (SNAME, ROLL, DEP) VALUES ('Madhan', 4343, 'MEC');
