INSERT INTO stud (ROLL, SNAME, DEPT, SEM) VALUES (101, 'ram', 'IT', 5);
INSERT INTO stud (ROLL, SNAME, DEPT, SEM) VALUES (102, 'rahim', 'IT', 3);
INSERT INTO stud (ROLL, SNAME, DEPT, SEM) VALUES (103, 'saravanan', 'CSE', 3);
INSERT INTO stud (ROLL, SNAME, DEPT, SEM) VALUES (104, 'Nataraj', 'IT', 3);
INSERT INTO stud (ROLL, SNAME, DEPT, SEM) VALUES (105, 'Elango', 'CSE', 5);


INSERT INTO placement (PLACEMENT_ID, ROLL, DEPT, COMPANY, SALARY) VALUES (1, 104, 'IT', 'infosys', 25000);
INSERT INTO placement (PLACEMENT_ID, ROLL, DEPT, COMPANY, SALARY) VALUES (2, 105, 'CSE', 'Wipro', 22000);
INSERT INTO placement (PLACEMENT_ID, ROLL, DEPT, COMPANY, SALARY) VALUES (3, 204, 'MECH', 'Hyundai', 30000);
INSERT INTO placement (PLACEMENT_ID, ROLL, DEPT, COMPANY, SALARY) VALUES (4, 102, 'IT', 'infosys', 25000);
INSERT INTO placement (PLACEMENT_ID, ROLL, DEPT, COMPANY, SALARY) VALUES (5, 103, 'CSE', 'infosys', 25000);
